#pip install ansible
#
#ansible all -m ping
#ansible all -i hosts.ini -m ping
#ansible-playbook playbook.yml
#ansible-playbook --connection=local 127.0.0.1, playbook.yml
#- name: "Ansible playbook example"
#  hosts: 127.0.0.1
#  connection: local
---
- name: gen_ansible
  hosts: all

  tasks:
  - name: ping
    ping:

  - name: copy
    copy:
        src: ../../json_redis/consumer.py
        dest: ./

  - name: run script
    ansible.builtin.script: consumer.py -e 1111111111,2222222222
    args:
        executable: python3
